import type { Hook } from "../../domain/hook.js";
import type { IgnorePattern } from "../../domain/ignore-pattern.js";
import type { EmitResult, EmittedFile } from "../types.js";

/** Cursor: ignore patterns → .cursorignore, hooks not directly emitted */
export function emitCursor(hooks: Hook[], ignorePatterns: IgnorePattern[]): EmitResult {
	const files: EmittedFile[] = [];
	const warnings: string[] = [];

	if (ignorePatterns.length > 0) {
		const lines = [
			"# Generated by dotai",
			"# File exclusion rules for Cursor AI",
			"",
			...ignorePatterns.map((p) => p.pattern),
			"",
		];
		files.push({
			path: ".cursorignore",
			content: lines.join("\n"),
		});
	}

	if (hooks.length > 0) {
		warnings.push(
			"Cursor hook support is limited — hooks are not directly emitted to Cursor config.",
		);
	}

	return { files, warnings };
}
